### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by RemarkWMHA** [RemarkWMHA/wmhacoaching#7]
- [x] Create form
- [ ] Integration of g form

Embedded HTML for google form
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfFu88BW0O9Ww68tFY_CGAyhUwRz-Jq0SuAG3ULblA2H1u4aQ/viewform?embedded=true" width="640" height="1498" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>

**Comment by nobe4** [comment]
The form is [on the page](https://wmhacoaching.com/contact/) but isn't available:

![Image](https://github.com/user-attachments/assets/d52ed6a1-a908-44ff-8426-a64a8e135723)

**Comment by RemarkWMHA** [comment]
Thank you for pointing it out, changed to Form settings, should work now.

**Comment by nobe4** [comment]
I submitted the form, so yeah :)
